// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI8m0ooPeaWrnsuLGThS-yDZw0qw5_b-o',
    appId: '1:133610598443:android:fda1a2e683c1d50e31ba6e',
    messagingSenderId: '133610598443',
    projectId: 'assan-ghar',
    storageBucket: 'assan-ghar.appspot.com',

    /*assan Ghar 
    apiKey: "AIzaSyAAWse7_Q2tRJ0va4vd1sr4FMNoedx-hqs",
    authDomain: "asaanghar-48e65.firebaseapp.com",
    projectId: "asaanghar-48e65",
    storageBucket: "asaanghar-48e65.appspot.com",
    messagingSenderId: "338569059419",
    appId: "1:338569059419:web:24772530246b4fb5e0f37e",
    */
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9mYcJ6sOLxPeJJmha2jhu64dn7x9nqQY',
    appId: '1:133610598443:ios:b7bb26010d343e5231ba6e',
    messagingSenderId: '133610598443',
    projectId: 'assan-ghar',
    storageBucket: 'assan-ghar.appspot.com',
    iosClientId:
        '133610598443-1evsuuacrpsoscdaacfm7aj095vvu067.apps.googleusercontent.com',
    iosBundleId: 'com.example.onboardAnimation',
  );
}
